apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealstore-frontend-node
  labels:
    app: dealstore-frontend-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dealstore-frontend-node
  template:
    metadata:
      labels:
        app: dealstore-frontend-node
    spec:
      containers:
      - name: dealstore-frontend
        image: waelamer/dealstore_frontend:2.0.1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dealstore-frontend-service
spec:
  selector:
    app: dealstore-frontend-node
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080